apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dinner
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: 12factor
      sourceRef:
        kind: HelmRepository
        name: lalyos
        namespace: default
      interval: 1m
  values:
    title: Have a nice weekend
    color: lightblue
